# --- Configuration des Sources ---
# On analyse la racine puisqu'il n'y a pas de dossier src
sonar.sources=.
sonar.sourceEncoding=UTF-8

# --- Configuration des Tests et Coverage ---
# Emplacement des tests (si tes tests sont dans un dossier "tests")
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# EXCLUSIONS CRITIQUES
# On doit exclure les tests de "sonar.sources" pour ne pas qu'ils soient analysés comme du code métier
# On exclut aussi les dossiers techniques
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, tests/**

# Chemin vers le rapport de couverture
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# --- Connexion Serveur ---
sonar.host.url=http://sonarqube:9000